import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { StorageProvider } from '../object-storage/storage.provider';

@Injectable()
export class ArtifactsService {
  constructor(
    @Inject(PrismaService) private readonly prisma: PrismaService,
    @Inject(StorageProvider) private readonly storage: StorageProvider
  ) {}

  async exportRun(runId: string) {
    const run = await this.prisma.workflowRun.findUnique({
      where: { id: runId },
      include: {
        nodeRuns: { orderBy: { startedAt: 'asc' } },
        workflow: true,
        workflowSnapshot: true,
        project: true
      }
    });
    if (!run) {
      throw new NotFoundException({ code: 'WORKFLOW_RUN_NOT_FOUND', message: 'WorkflowRun 不存在' });
    }
    if (run.status !== 'succeeded' && run.status !== 'exported') {
      throw new BadRequestException({ code: 'RUN_NOT_EXPORTABLE', message: '只有成功完成的 WorkflowRun 可以导出' });
    }

    await this.prisma.workflowRun.update({ where: { id: runId }, data: { status: 'exporting' } });
    const packageBody = {
      schemaVersion: 'material-package.v1',
      project: {
        id: run.projectId,
        name: run.project.name
      },
      workflow: {
        id: run.workflowId,
        name: run.workflow?.name ?? (run.workflowSnapshot?.snapshot as { workflow?: { name?: string } } | null)?.workflow?.name
      },
      workflowRun: {
        id: run.id,
        source: run.source,
        initialInput: run.initialInput,
        finishedAt: run.finishedAt
      },
      outputs: (run.controlState as { outputs?: Record<string, unknown> } | null)?.outputs ?? {},
      nodeRuns: run.nodeRuns.map((nodeRun) => ({
        id: nodeRun.id,
        workflowNodeId: nodeRun.workflowNodeId,
        status: nodeRun.status,
        input: nodeRun.input,
        output: nodeRun.editedOutput ?? nodeRun.output,
        usage: nodeRun.usage,
        startedAt: nodeRun.startedAt,
        finishedAt: nodeRun.finishedAt
      }))
    };

    const manifest = {
      schemaVersion: 'artifact-manifest.v1',
      projectId: run.projectId,
      workflowRunId: run.id,
      workflowId: run.workflowId,
      workflowSnapshotId: run.workflowSnapshotId,
      generatedAt: new Date().toISOString(),
      files: ['README.md', 'manifest.json', 'material-package.json']
    };
    const body = createZip([
      {
        name: 'README.md',
        content: Buffer.from(
          [
            '# Material Package',
            '',
            'This package was generated by Agents OS.',
            '',
            `WorkflowRun: ${run.id}`,
            `Project: ${run.project.name}`,
            '',
            'Open material-package.json for structured node outputs and trace data.'
          ].join('\n'),
          'utf8'
        )
      },
      { name: 'manifest.json', content: Buffer.from(JSON.stringify(manifest, null, 2), 'utf8') },
      { name: 'material-package.json', content: Buffer.from(JSON.stringify(packageBody, null, 2), 'utf8') }
    ]);
    const objectKey = `projects/${run.projectId}/runs/${run.id}/package.zip`;
    const stored = await this.storage.putObject({
      objectKey,
      body,
      contentType: 'application/zip'
    });

    const artifact = await this.prisma.artifact.create({
      data: {
        projectId: run.projectId,
        workflowRunId: run.id,
        type: 'material_package',
        objectKey: stored.objectKey,
        filename: 'package.zip',
        contentType: 'application/zip',
        sizeBytes: stored.sizeBytes,
        metadata: { manifest, package: packageBody } as Prisma.InputJsonValue
      }
    });

    await this.prisma.workflowRun.update({ where: { id: runId }, data: { status: 'exported' } });
    return artifact;
  }

  async getDownload(artifactId: string) {
    const artifact = await this.prisma.artifact.findUnique({ where: { id: artifactId } });
    if (!artifact) {
      throw new NotFoundException({ code: 'ARTIFACT_NOT_FOUND', message: 'Artifact 不存在' });
    }
    return {
      artifactId,
      filename: artifact.filename,
      contentType: artifact.contentType,
      url: await this.storage.getDownloadUrl(artifact.objectKey)
    };
  }
}

type ZipEntry = {
  name: string;
  content: Buffer;
};

const crcTable = Array.from({ length: 256 }, (_, index) => {
  let value = index;
  for (let bit = 0; bit < 8; bit += 1) {
    value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
  }
  return value >>> 0;
});

function crc32(buffer: Buffer) {
  let value = 0xffffffff;
  for (const byte of buffer) {
    value = (value >>> 8) ^ crcTable[(value ^ byte) & 0xff];
  }
  return (value ^ 0xffffffff) >>> 0;
}

function dosTime(date = new Date()) {
  const time =
    (date.getHours() << 11) |
    (date.getMinutes() << 5) |
    Math.floor(date.getSeconds() / 2);
  const day =
    ((date.getFullYear() - 1980) << 9) |
    ((date.getMonth() + 1) << 5) |
    date.getDate();
  return { time, day };
}

function createZip(entries: ZipEntry[]) {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let offset = 0;
  const { time, day } = dosTime();

  for (const entry of entries) {
    const name = Buffer.from(entry.name, 'utf8');
    const crc = crc32(entry.content);
    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt16LE(0x0800, 6);
    localHeader.writeUInt16LE(0, 8);
    localHeader.writeUInt16LE(time, 10);
    localHeader.writeUInt16LE(day, 12);
    localHeader.writeUInt32LE(crc, 14);
    localHeader.writeUInt32LE(entry.content.length, 18);
    localHeader.writeUInt32LE(entry.content.length, 22);
    localHeader.writeUInt16LE(name.length, 26);
    localHeader.writeUInt16LE(0, 28);
    localParts.push(localHeader, name, entry.content);

    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(0x02014b50, 0);
    centralHeader.writeUInt16LE(20, 4);
    centralHeader.writeUInt16LE(20, 6);
    centralHeader.writeUInt16LE(0x0800, 8);
    centralHeader.writeUInt16LE(0, 10);
    centralHeader.writeUInt16LE(time, 12);
    centralHeader.writeUInt16LE(day, 14);
    centralHeader.writeUInt32LE(crc, 16);
    centralHeader.writeUInt32LE(entry.content.length, 20);
    centralHeader.writeUInt32LE(entry.content.length, 24);
    centralHeader.writeUInt16LE(name.length, 28);
    centralHeader.writeUInt16LE(0, 30);
    centralHeader.writeUInt16LE(0, 32);
    centralHeader.writeUInt16LE(0, 34);
    centralHeader.writeUInt16LE(0, 36);
    centralHeader.writeUInt32LE(0, 38);
    centralHeader.writeUInt32LE(offset, 42);
    centralParts.push(centralHeader, name);
    offset += localHeader.length + name.length + entry.content.length;
  }

  const central = Buffer.concat(centralParts);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(central.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(0, 20);
  return Buffer.concat([...localParts, central, end]);
}
